# Generated by Django 5.2.10 on 2026-03-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('GB', 'United Kingdom'), ('IE', 'Ireland')], max_length=2),
        ),
    ]
